apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterspiffeids.spiffeid.spiffe.io
spec:
  group: spiffeid.spiffe.io
  names:
    kind: ClusterSpiffeId
    listKind: ClusterSpiffeIdList
    plural: clusterspiffeids
    singular: clusterspiffeid
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ClusterSpiffeId is the Schema for the spiffeids API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SpiffeIdSpec defines the desired state of SpiffeId
          properties:
            selector:
              description: Selectors to match for this ID
              properties:
                podLabel:
                  additionalProperties:
                    type: string
                  description: Pod label names/values to match for this spiffe ID
                    To match, pods must be in the same namespace as this ID resource.
                  type: object
                podName:
                  type: string
              required:
              - podLabel
              - podName
              type: object
            spiffeId:
              description: The Spiffe ID to create
              type: string
          required:
          - selector
          - spiffeId
          type: object
        status:
          description: SpiffeIdStatus defines the observed state of SpiffeId
          properties:
            entryId:
              description: The spire Entry ID created for this Spiffe ID
              type: string
          required:
          - entryId
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
